### PR TITLE
Screenshot Visualizer and some layout changes

### PR DESCRIPTION
**Pull request by simeonradivoev**
Some of the changes:
* Added optional icons to Detail Info (Can be disabled using Theme Modifier)
* Moved description and other extension info to tabs
* Added support for screenshot visualizer
* Added custom Success Story achievement list
* Added Success Story Button that shows achievement progress
* Added unlocked and locked achievements and screenshots below the details column
* Made Uninstalled icons in the games list transparent
* Added git ignore
* Removed obj folder

I also bumped the version to 1.2 since there were a lot of changes, would understand if you don't want to merge since it does change the description area a bit

### CODE REVIEW

**Comment by darklinkpower** [comment]
Sorry for the delay in the reply. I'll try to take a look and review all the next week, although there are some things I can point out:
* Using tabs for the different plugins is a great idea, initially that's what I wanted to do in the theme but they had some bugs that prevented their content from being loaded when being integrated this way for some reason. The bugs were eventually fixed but never got to change this change is great.
* I think if icons are implemented for the different game properties in details, the change should be added to the details panel in the grid view for consistency, not only in details view.
* Also regarding the icons, I'm not completely comfortable with this change because while some icons do match the property name (Like in community score, Time played, Links, Etc) some do not (Like Genres, developers, publisher, features, etc). I have no problem adding it as an optional feature but I'm not sure if this should be enabled by default for this reason. I checked other clients to see what they did and none of them use icons I suspected for the same reason.

**Comment by simeonradivoev** [comment]
* For the icons yea, I agree they should be disabled by default, but not sure how to do that. Is there a way to store the user choice so it doesn't reset when you restart the app?
* Yes tabs are hidden if the plugins are disabled/or there is no data for a game
One issue is if you switch to a tab and then switch the game and it doesn't have data for that tab, let's say achievement, the tab is still selected even when hidden, not sure how to default to a non-hidden tab. (this only causes blank tab contents nothing else)

**Comment by darklinkpower** [comment]
When ThemeModifier is enabled, any constant you edit here will be modified on runtime and affect the theme.
image

It doesn't modify the constant file permantently so it needs to stay enabled. What buttons do you mean exactly?

**Comment by darklinkpower** [comment]
Yeah I'll add something for this in a future update.
By the way, do you know if there is any way to sort the achievements in the custom presenter by either date or locked/unlocked status?

Also changes are only permanent if you either modify the constant in the theme constants file or if you edit the constant in the ThemeModifier theme settings. There's no way other than that to save the state of the buttons otherwise.

**Comment by simeonradivoev** [comment]
I don't think there is a way to sort the achievements. It must be done plugin side.

**Comment by darklinkpower** [comment]
I've added a button to hide the buttons, it is invisible until hover

image

To make the default behaviour permanent the theme constant needs to be modifier using ThemeModifier or manually
https://github.com/darklinkpower/Stardust/wiki#editing-theme-settings

image

I'll change the default value to `False` when Playnite 9 releases.

**Pull request closed without merging**
